quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Cangrejo
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/crm_juridico

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi