quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=crm_user
quarkus.datasource.password=DDHcPIxZbOE3hpQWhC25XQ6e6n1ryFdt
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d7f7aui8qa3s73alaga0-a.oregon-postgres.render.com:5432/crm_juridico

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,origin